[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# remappings 

fs_permissions = [
    { access = "read", path = "./ratio.json"},
    { access = "write", path = "./artifacts/uniswap_addresses_dev.json"},
    { access = "read", path = "./artifacts/uniswap_addresses_dev_read.json"},
]

# optimizer = true
optimizer_runs = 200
via_ir = false
